name: dist-s1-model
channels:
  - conda-forge
channel_priority: strict
dependencies:
 - python>=3.12,<3.13
 - accelerate
 - asf_search
 - backoff
 - compilers
 - einops
 - flake8
 - flake8-blind-except
 - flake8-builtins
 - flake8-import-order
 - gdal
 - geopandas
 - jupyterlab
 - matplotlib
 - numpy
 - pandas
 - pydantic
 - pytest
 - pytest-cov
 - pytorch
 - rasterio>=1.4.0  # merge was improved in minor release
 - requests
 - ruff
 - scikit-image
 - scipy
 - setuptools
 - setuptools_scm
 - shapely
 - tqdm
 - wandb
 - pip 
 - pip:
   # These must be installed in this order (see: https://docs.pytorch.org/TensorRT/getting_started/installation.html#installation)
   - torch-tensorrt
   - tensorrt
   - nvidia-modelopt[all]
