name: dist-s1-model
channels:
  - conda-forge
channel_priority: strict
dependencies:
 - python>=3.12
 - asf_search
 - backoff
 - compilers
 - cudatoolkit>=11.8
 - einops
 - flake8
 - flake8-blind-except
 - flake8-builtins
 - flake8-import-order
 - gdal
 - geopandas
 - jupyterlab
 - matplotlib
 - numpy
 - pandas
 - pydantic
 - pytest
 - pytest-cov
 - pytorch
 - rasterio>=1.4.0  # merge was improved in minor release
 - requests
 - ruff
 - scikit-image
 - scipy
 - setuptools
 - setuptools_scm
 - shapely
 - tqdm
 - wandb
 - pip:
   - tensorrt
   - torch 
   - torchvision 
   - torchaudio
   - torch-tensorrt
   - nvidia-modelopt[all]